version: 2
jobs:
  build:
    working_directory: ~/defective-project
    docker:
      - image: circleci/python3.6.7
    steps:
      - checkout
      - run:
          name: run test
          command: |
            python -m unittest discover tests
